name: 03. Deploy image tag to testenv

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: Image tag to deploy


concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-to-testenv:
    runs-on: ubuntu-22.04
    env:
      VAR_FRONTEND_REPOSITORY: ${{ vars.FRONTEND_REPOSITORY }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.5.0
        with:
          ref: "${{ github.event.inputs.image-tag }}"

      - name: Get branch name and commit SHA
        id: get-branch
        uses: ./.github/actions/get-branch


      - name: Check if commit status is 'success'
        shell: bash
        run: |
          curl --http1.1 -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CI_GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mikogs/project-template-frontend/commits/${{ steps.get-branch.outputs.sha_long }}/status | jq -r .state > status_output
          
          cat status_output
          cat status_output | grep 'success'

      - name: Pull the image to check if it exists
        env:
          DOCKER_IMAGE: ${{ vars.FRONTEND_REPOSITORY }}:${{ github.event.inputs.image-tag }}
        run: |
          docker pull ${DOCKER_IMAGE}


      - name: GIT | Checkout project-template-apps-frontend repository
        uses: actions/checkout@master
        with:
          repository: mikogs/project-template-apps-frontend
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: "project-template-apps-frontend"

      - name: Init kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.8.6"

      - name: Replace image tag for testenv
        env:
          DOCKER_IMAGE: ${{ vars.FRONTEND_REPOSITORY }}:${{ github.event.inputs.image-tag }}
        run: |
          cd project-template-apps-frontend/overlays/testenv/
          for r in region region2 region3; do
            cd $r
            kustomize edit set image "frontend-image-placeholder=${DOCKER_IMAGE}"
            cd ..
          done

      - name: Commit changes to project-template-apps-frontend repository
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: project-template
          author_email: project-template@f0x.pl
          message: "Update testenv frontend docker image tag to: ${{ github.event.inputs.image-tag }}"
          add: "*.yaml"
          cwd: "project-template-apps-frontend"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}


      - name: Checkout project-template-envs repository
        uses: actions/checkout@master
        with:
          repository: mikogs/project-template-envs
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: "project-template-envs"
          submodules: "recursive"

      - name: Update testenv/frontend submodule
        run: |
          cd project-template-envs
          git submodule update --remote testenv/frontend
      
      - name: Commit changes to project-template-envs repository
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: project-template
          author_email: project-template@f0x.pl
          message: "Update testenv frontend docker image tag to: ${{ github.event.inputs.image-tag }}"
          add: "testenv/frontend"
          cwd: "project-template-envs"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
